[package]
name = "yuu-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.5.0", features = ["auto-color"] }
logos = "0.14.2"
ron = "0.8.1"
serde = "1.0.215"
thiserror = "2.0.3"
yuu-shared = { path = "../yuu-shared" }
