[package]
name = "yuu-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
logos = "0.15.0"
ron = "0.8.1"
serde = "1.0.215"
thiserror = "2.0.3"
yuu-shared = { path = "../yuu-shared" }
