[package]
name = "yuu-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
yuu-shared = { path = "../yuu-shared" }
yuu-transform = { path = "../yuu-transform" }
yuu-parse = { path = "../yuu-parse" }
anyhow = "1.0.95"
hashbrown = "0.15.2"
#inkwell = "0.5.0"
