[package]
name = "yuu-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
yuu-shared = { path = "../yuu-shared" }
yuu-transform = { path = "../yuu-transform" }
yuu-parse = { path = "../yuu-parse" }
anyhow = "1.0.95"
ustr = { version = "1.1.0", features = ["serde"] }
#inkwell = "0.5.0"
