[package]
name = "yuu-transform"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
hashbrown = "0.15.1"
serde_json = "1.0.134"
thiserror = "2.0.3"
yuu-parse = { path = "../yuu-parse" }
yuu-shared = { path = "../yuu-shared" }
