[package]
name = "yuu-transform"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.5.0", features = ["auto-color"] }
hashbrown = "0.15.1"
thiserror = "2.0.3"
yuu-parse = { path = "../yuu-parse" }
yuu-shared = { path = "../yuu-shared" }
